"""Update Section Model to include order_num column

Revision ID: 991d4218408b
Revises: c8b33d6cf201
Create Date: 2021-03-22 03:41:00.339951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991d4218408b'
down_revision = 'c8b33d6cf201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('order_num', sa.Integer(), nullable=False))
    op.drop_column('sections', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('sections', 'order_num')
    # ### end Alembic commands ###
